### ISSUE TITLE
Install docker with corresponding Ubuntu distribution name

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#163]
In `docker.yml`, the distribution name is hard coded:
```
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
```
`bionic` corresponds to Ubuntu 18.04. For Ubuntu 20.04, it is `focal`.
It should be better to have the correct distribution name. If it cannot be detected automaticaly, maybe we could pass the distrib name as server variable in the `hosts` file.
