### ISSUE TITLE
Define JupyterHub admin users in user config yaml file

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#168]
For instance:
```yaml
plasma_groups:
  - group_1
  - group_2
  - group_3

users:
  - name: foo
    password: PLAIN_TEXT_PASSWORD
    groups:
      - group_1
      - group_2
    admin: true

  - name: bar
    password: PLAIN_TEXT_PASSWORD
    groups:
      - group_3
```
