### ISSUE TITLE
Update repo2docker docker image

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#190]
Running the `tljh.yml` playbook does not the update the repo2docker Docker image.
For that, the `force_source: True` parameter is needed in the corresponding rule:
```
    # Pull the repo2docker image to build user images
    - name: Pull jupyter/repo2docker
      docker_image:
        name: jupyter/repo2docker
        tag: master
        source: pull
        force_source: True
```

Doing that, running the playbook indeed updates the repo2docker image. It also keeps the former image that may or may not expected.

Unfortunately, building environments with this new repo2docker image is failing...
